### ISSUE TITLE
Two step Authentication doesn't work

### ISSUE THREAD

**Issue by poriyaMH** [narbehaj/instagram-status#3]
I Can't login with Two step Authentication/Vertification enabled. I believe that the problem is the API.
Why shouldn't the script use the official API? So that authentication(also two step vertification) is handled by Instagram and it will return a token.

**Comment by narbehaj** [comment]
Right, unfortunately, we are using @Levpasha's Instagram API which does not support two-step auth yet. Since we are using that API, we need to sit back and wait for the implementation or we can go for another API if you know a better one.

**Comment by poriyaMH** [comment]
Is is possible to use the official Instagram API?

**Comment by narbehaj** [comment]
Well, the thing is, AFAIK, they don't have an official python API like the one we use at the moment. They only provide methods.
